name: ees-data-screener-$(rev:r)

pool:
  name: RSConnect
  
trigger:
  branches:
    include:
    - main
    - master
  paths:
    exclude:
    - azure-pipelines.yml
    
resources:
  repositories:
    - repository: posit-deploy
      type: git
      name: ESFA-Data-Science/posit-deploy
      
extends:
  template: deploy.yml@posit-deploy
  parameters:
    appName: dfe-published-data-qa
    environments:
    - name: Pre-Production
      appId: 459
    - name: Production
      appId: 123
    approvers: |
     cameron.race@education.gov.uk
     laura.selby@education.gov.uk
     richard.bielby@education.gov.uk