app <- ShinyDriver$new("../../")
app$snapshotInit("qa_tabs_UI_tests", screenshot = FALSE)

app$uploadFile(datafile = "test-data/passes_everything.csv") # <-- This should be the path to the file, relative to the app's tests/shinytest directory
app$uploadFile(metafile = "test-data/passes_everything.meta.csv") # <-- This should be the path to the file, relative to the app's tests/shinytest directory
app$setInputs(screenbutton = "click")
app$snapshot()
app$setInputs(trendy_tabs = "previewTab")
app$snapshot()
app$setInputs(trendy_tabs = "obUnitTab")
app$snapshot()
app$setInputs(trendy_tabs = "indicatorsTab")
app$setInputs(submit = "click")
app$snapshot()
app$setInputs(ind_parameter = "num_schools")
app$setInputs(submit = "click")
Sys.sleep(2)
app$snapshot()
app$setInputs(ind_parameter = character(0))
app$setInputs(geog_parameter = "National")
app$setInputs(geog_parameter = c("National", "Regional"))
app$setInputs(geog_parameter = c("National", "Regional", "Local authority"))
app$setInputs(geog_parameter = c("National", "Regional", "Local authority", "Local authority district"))
Sys.sleep(2)
app$setInputs(submit = "click")
app$snapshot()
app$setInputs(ind_parameter = c("num_schools", "enrolments"))
Sys.sleep(2)
app$setInputs(submit = "click")
app$snapshot()
app$setInputs(trendy_tabs = "outliersTab")
app$setInputs(submit_outlier = "click")
app$snapshot()
app$setInputs(comptime_parameter = "201617")
app$setInputs(submit_outlier = "click")
Sys.sleep(2)
app$snapshot()
app$setInputs(outlier_indicator_parameter = "num_schools")
app$setInputs(comptime_parameter = "201718")
app$setInputs(submit_outlier = "click")
Sys.sleep(2)
app$snapshot()
app$setInputs(threshold_setting = 5)
app$setInputs(outlier_indicator_parameter = c("num_schools", "sess_overall_percent"))
app$setInputs(comptime_parameter = "201617")
app$setInputs(submit_outlier = "click")
Sys.sleep(2)
app$snapshot()
app$setInputs(trendy_tabs = "geogTab")
app$setInputs(submit_geographies = "click")
app$snapshot()
app$setInputs(geog_indicator_parameter = "num_schools")
app$setInputs(submit_geographies = "click")
Sys.sleep(2)
app$snapshot()
app$setInputs(trendy_tabs = "tab1")
app$setInputs(resetbutton = "click")
app$uploadFile(datafile = "test-data/passes_everything_ancillary.csv") # <-- This should be the path to the file, relative to the app's tests/shinytest directory
app$uploadFile(metafile = "test-data/passes_everything_ancillary.meta.csv") # <-- This should be the path to the file, relative to the app's tests/shinytest directory
app$setInputs(screenbutton = "click")
app$snapshot()
