on:
  push:
    branches:
      - master
  pull_request:

name: tidyCode

jobs:
  tidyCode:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest, r: 'release'}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}
      RENV_PATHS_ROOT: ~/.local/share/renv

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v4
        with:
          use-public-rspm: true

      - name: Cache R packages
        if: runner.os != 'Windows'
        uses: actions/cache@v4
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-

      - name: Cache renv packages
        uses: actions/cache@v4
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-
        
      - name: Restore renv snapshot
        shell: Rscript {0}
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          renv::restore()
      
      - name: Tidy code
        shell: Rscript {0}
        run: |
            codeChecks <- eval(styler::style_dir()$changed)

            if(any(is.na(codeChecks))) {
              stop("There is a breaking error in the code.")
            } else {
              if(TRUE %in% codeChecks) {
                stop("The code is not styled correctly. Open the project in RStudio and use styler::style_dir() to restyle the code.")
              } else {
                message("")
                message(praise::praise("${Exclamation}! This code is ${Adjective}, go you!"))
                message(""")
              }
            }

      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@master
        with:
          name: ${{ runner.os }}-r${{ matrix.config.r }}-tests
          path: tests
